package com.uralian.cgiats.model;

public enum IndiaSubmittalStatus {

	SUBMITTED, DMREJ, ACCEPTED, INTERVIEWING, TECH_SELECTED, TECH_REJECTED, HR_SELECTED, HR_REJECTED, 
	OFFER_ACCEPTED, OFFER_REJECTED, STARTED, BACKOUT
}
