package com.uralian.cgiats.model;

public enum OfferLetterStatus 
{
	    OFFER_LETTER_CREATED,
	    OFFER_LETTER_SAVED,
	    FIRST_CONTACT_MADE_PRE_OFFER_DISCUSSION,
	    OFFER_LETTER_SUBMITTED,  
	    OFFER_LETTER_REQUEST_NOT_RECEIVED,
	    OFFER_LETTER_REQUEST_RECEIVED,	
	    OFFER_LETTER_SENT_TO_CONSULTANT,
	    BACKGROUND_CHECK_INITIATED,
     	DRUG_TEST_INITIATED,
		SIGNED_OFFER_RECEIVED,
		BENEFITS_ENROLLMENT_FORMS_BEING_SENT_OUT,
		BENEFITS_ENROLLMENT_FORMS_NOT_RECEIVED,
		BENEFITS_ENROLLMENT_FORMS_RECEIVED,
		CANDIDATE_ON_BOARDED,
		CANDIDATE_BACKED_OUT
}
